### ISSUE TITLE
Borra ficheros de copia de seguridad 

### ISSUE THREAD

**Issue by JJ** [rogegg/AppOrganizacionEmpresas#10]
Los del ~ al final. Y añadelos a .gitignore.

**Comment by rogegg** [comment]
Eliminados ficheros de copia de seguridad y añadidos a .gitignore

**Comment by JJ** [comment]
con un commit!

Puedes poner en el mensaje del commit simplemente "closes #10"

2015-03-24 12:56 GMT+01:00 Rogelio notifications@github.com:

> Eliminados ficheros de copia de seguridad y añadidos a .gitignore
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rogegg/AppOrganizacionEmpresas/issues/10#issuecomment-85466239
> .

## 

JJ
