### ISSUE TITLE
Usar QUnit para test

### ISSUE THREAD

**Issue by JJ** [rogegg/AppOrganizacionEmpresas#12]
https://qunitjs.com/

Toda funcionalidad debe tener su test unitario.

**Comment by JJ** [comment]
¿Has mirado esto?

**Comment by rogegg** [comment]
Si les he echado un vistazo, pero no los he incluido aún. Me pongo con Bower y Qunits

**Comment by JJ** [comment]
Le echo un vistazo con @germaaan a ver qué se puede hacer cuando acabe con lo que tiene.

**Comment by germaaan** [comment]
Probando.

**Comment by germaaan** [comment]
Quizás sería interesante con el QUnit testear a nivel de DOM: 
http://forum.jquery.com/topic/start-with-qunit
http://stackoverflow.com/questions/7620971/how-to-test-against-a-dom-object-in-qunit
http://stackoverflow.com/questions/3974147/how-can-we-execute-unit-tests-against-dom-manipulation
