### ISSUE TITLE
Popup para definiciones y ejemplos

### ISSUE THREAD

**Issue by rogegg** [rogegg/AppOrganizacionEmpresas#14]
Dentro de la lista desplegable de conceptos hay que ubicar las definiciones y ejemplos.

Editado: Cuando se seleccione un concepto aparecerá con un popup la definición y ejemplo.

**Comment by JJ** [comment]
¿Esto es un error? ¿Una tarea?

**Comment by rogegg** [comment]
Es una tarea. Hay una lista desplegable en la sección de "Conceptos" de la aplicación con subniveles para llegar a las definiciones y ejemplos de los conceptos.

El esquema es: 

> Variable
> 
> > |---Subvariable
> > 
> > > |---Concepto
> > > 
> > > > |---Definición
> > > > |---Ejemplo

**Comment by rogegg** [comment]
Cuando se seleccione un concepto aparecerá con un popup la definición y ejemplo.

**Comment by germaaan** [comment]
Miro esto.
