### ISSUE TITLE
Maqueta de la App

### ISSUE THREAD

**Issue by rogegg** [rogegg/AppOrganizacionEmpresas#2]
Pendiente de acordar la estructura de la aplicación así como su organización.

Actualizado:
Secciones de la maqueta:
- [Conceptos](https://github.com/rogegg/AppOrganizacionEmpresas/issues/6)
- [Preguntas cortas](https://github.com/rogegg/AppOrganizacionEmpresas/issues/17)
- [Preguntas Verdadero/Falso](https://github.com/rogegg/AppOrganizacionEmpresas/issues/18)

**Comment by JJ** [comment]
Trata de usar alguna herramienta libre de creación de mockups. No sé cuál
habrá, pero seguro que la hay.

JJ

**Comment by rogegg** [comment]
Ok, he estado viendo [Pencil Project](http://pencil.evolus.vn/) que tiene buena pinta.

**Comment by JJ** [comment]
Efectivamente. Recuerda que la maqueta de la aplicación es algo que tiene
que aprobar el "cliente", en este caso los investigadores del proyecto.

**Comment by rogegg** [comment]
Codiqa también presenta una herramienta online gratuita, y tiene un UI de jQuery Mobile
https://codiqa.com

**Comment by JJ** [comment]
Si has terminado la maqueta y te la han aprobado, cierra esto. Si es posible con un commit.

**Comment by rogegg** [comment]
Sólo han aprobado la parte de conceptos. Falta:
- [Preguntas cortas](https://github.com/rogegg/AppOrganizacionEmpresas/issues/17)
- [Preguntas Verdadero/Falso](https://github.com/rogegg/AppOrganizacionEmpresas/issues/18)
