### ISSUE TITLE
Reorganización repositorio

### ISSUE THREAD

**Issue by JJ** [rogegg/AppOrganizacionEmpresas#29]
Separar en un repositorio la aplicación móvil para que sea fácil de desplegar y colocarla como un submódulo de todo el proyecto para mantenerlo junto.

**Comment by rogegg** [comment]
Añadido submódulo para código fuente.

Solucionado con [e937355](https://github.com/rogegg/AppOrganizacionEmpresas/commit/e93735533e7a9d0296cf7854aa2b0c84ec5007b9)
