### ISSUE TITLE
Probar alternativas a jquery mobile

### ISSUE THREAD

**Issue by JJ** [rogegg/AppOrganizacionEmpresas#31]
Por ejemplo http://www.gajotres.net/top-7-notable-less-known-mobile-html5-frameworks/
O lungo: http://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0CDQQFjAC&url=http%3A%2F%2Fwww.quora.com%2FWhat-are-some-alternatives-to-jQuery-Mobile&ei=5U4uVY2LF6Hm7gaIiIHQAg&usg=AFQjCNHxUytIlw8TVaeD91pyUnNogc33xw&sig2=lJFSEWevLpd-Vh4FcmzTKA&bvm=bv.90790515,d.ZGU o cualquiera de esas...

**Comment by rogegg** [comment]
Probando [Ionic](http://ionicframework.com/) y [Lungo](http://lungo.tapquo.com/)
