### ISSUE TITLE
Nombre de la App

### ISSUE THREAD

**Issue by rogegg** [rogegg/AppOrganizacionEmpresas#4]
Preguntar al cliente sobre el nombre de la aplicación

**Comment by JJ** [comment]
Será el nombre...

**Comment by rogegg** [comment]
Más bien... jeje. Corregido

**Comment by JJ** [comment]
¿Esto no está resuelto? No debes dejar que los issues se queden tanto tiempo abiertos... lo importante es ir cubriendo hitos.

**Comment by rogegg** [comment]
El cliente me acaba de enviar el nombre de la aplicación: " iOrg "

**Comment by JJ** [comment]
iArg
