### ISSUE TITLE
Integrar sistema de plantillas.

### ISSUE THREAD

**Issue by rogegg** [rogegg/AppOrganizacionEmpresas#8]
@JJ recomienda el uso de un sistema de plantillas.Un ejemplo junto a jQueryMobile 

[http://www.gajotres.net/using-jquery-mobile-with-handlebars/](http://www.gajotres.net/using-jquery-mobile-with-handlebars/)

**Comment by rogegg** [comment]
Añadida una prueba para comprender el compilado de las plantillas.

**Comment by rogegg** [comment]
Ya trabajando con las plantillas Handlebars

**Comment by JJ** [comment]
Trata de cerrar siempre con un commit.
Y trata de hacer test de código y de lo que implementes. No lo dejes
simplemente cerrado.

2015-03-24 12:22 GMT+01:00 Rogelio notifications@github.com:

> Ya trabajando con las plantillas Handlebars
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rogegg/AppOrganizacionEmpresas/issues/8#issuecomment-85455133
> .

## 

JJ
